### ISSUE TITLE
Cronjob entry - proper setup

### ISSUE THREAD

**Issue by lboc80** [isl-x/django-rq-scheduler#27]
I'm using the latest master version of django-rq-scheduler with django 1.11.13.
I created those cronjobs using the cronjob admin:

![ss_detail](https://user-images.githubusercontent.com/6185656/43141580-8cd4ee1c-8f56-11e8-9419-eb2bc7908654.png)
![ss_before](https://user-images.githubusercontent.com/6185656/43141590-959b6d28-8f56-11e8-8646-c7bf81d32482.png)

eg. the 'Process Queues' jobs, expected to run every 10 mins, runs fine but at some points it stops to run.
In fact, after few runs, the 'is scheduled' value change from True to False:

I think is the value of the 'repeat' field, which I sue to set to 1, but it's not clear to me what is supposed to do, the docs does not say much.
Any help about that?

**Comment by g3rd** [comment]
HI @lboc80,
Is this still an issue?
